sude: required
services: -dokcer
before_install:
  - docker build -t gauravlfc93/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gauravlfc93/react-test npm run test

after_success:
  - docker build -t gauravlfc93/multi-client ./client
  - docker build -t gauravlfc93/multi-nginx ./nginx
  - docker build -t gauravlfc93/multi-server ./server
  - docker build -t gauravlfc93/multi-worker ./worker
  # Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hum
  - docker push gauravlfc93/multi-client
  - docker push gauravlfc93/multi-nginx
  - docker push gauravlfc93/multi-server
  - docker push gauravlfc93/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-935284059124
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
